EXTERNAL_TOOLCHAIN = "/opt/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu"
TOOLCHAIN_PREFIX = "aarch64-none-linux-gnu-"

HR_SDK_DIR = "${TOPDIR}/../horizon-sdk"
HR_SDK_UBOOT_DIR = "${HR_SDK_DIR}/platform_source_code/uboot"
HR_SDK_MINIBOOT_DIR = "${HR_SDK_DIR}/platform_source_code/miniboot"

HR_BUILD_OUTPUT_DIR = "${TOPDIR}/../out"
HR_TARGET_DEPLOY_DIR = "${HR_BUILD_OUTPUT_DIR}/deploy"
HR_UBOOT_OUTPUT_DIR = "${HR_BUILD_OUTPUT_DIR}/build/u-boot"



